name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # 可以更改为 'beta' 或 'dev' 通道
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check for formatting issues
        run: flutter format --set-exit-if-changed .
      
      - name: Analyze project
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
      
      - name: Build APK (Android)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          flutter build apk --release
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
      
      - name: Build App Bundle (Android)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          flutter build appbundle --release
          cp build/app/outputs/bundle/release/app-release.aab artifacts/
      
      - name: Build iOS (Simulator)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          flutter build ios --simulator --release
          mkdir -p artifacts/ios
          cp -r build/ios/iphoneos/Runner.app artifacts/ios/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: flutter-build
          path: artifacts/
